---
- name: Core setup of hosts
  hosts: all
  remote_user: ansible
  roles:
    - ssh
    - admin_users
    - firewall

- name: Install MTProxyMax
  hosts: mtproxymax_hosts
  remote_user: ansible
  roles:
    - mtproxymax

- name: Install 3X-UI
  hosts: x_ui_hosts
  remote_user: ansible
  roles:
    - x_ui_inbounds
