---
- name: Reload UFW if it is already active
  community.general.ufw:
    state: reloaded
  become: true
  when:
    - "'Status: active' in firewall_ufw_status.stdout"
  changed_when: false
  listen: reload ufw
