---
- name: Configure vmagent
  tags: [vmagent, monitoring]
  become: true
  block:
    - name: Ensure vmagent config directory exists
      ansible.builtin.file:
        path: /etc/vmagent
        state: directory
        mode: "0755"

    - name: Configure vmagent to scrape node_exporter and write to central VictoriaMetrics
      ansible.builtin.template:
        src: "{{ role_path }}/templates/vmagent_config.yaml.j2"
        dest: /etc/vmagent/scrape.yml
        mode: "0644"

- name: Run vmagent container
  community.docker.docker_container:
    name: vmagent
    image: "victoriametrics/vmagent:{{ vmagent_version }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - /etc/vmagent/scrape.yml:/etc/vmagent/scrape.yml
    command:
      - "-promscrape.config=/etc/vmagent/scrape.yml"
      - "-remoteWrite.url=http://{{ victoriametrics_server_fqdn }}:8428/api/v1/write"
      - "-remoteWrite.basicAuth.username={{ victoriametrics_user }}"
      - "-remoteWrite.basicAuth.password={{ victoriametrics_password }}"
      - "-httpListenAddr=:{{ vmagent_port }}"
      - "-remoteWrite.label=node={{ inventory_hostname }}"
  become: true
  tags: [vmagent, monitoring]
