---
galaxy_info:
  role_name: victoriametrics
  description: Runs the central VictoriaMetrics storage container
  min_ansible_version: "2.15"

dependencies:
  - role: geerlingguy.docker
    tags: [docker]
