# handlers/main.yml
---
- name: Validate sshd configuration
  ansible.builtin.command: sshd -t
  changed_when: false
  listen: Restart ssh

- name: Restart ssh
  ansible.builtin.service:
    name: "{{ ssh_hardening_service_name }}"
    state: restarted
  listen: Restart ssh
