---
- name: Run VictoriaMetrics container
  community.docker.docker_container:
    name: victoria-metrics
    image: victoriametrics/victoria-metrics:latest
    state: started
    restart_policy: unless-stopped
    network_mode: host
    command:
      - '-storageDataPath=/storage'
      - '-retentionPeriod={{ vm_retention_period }}'
      - '-httpListenAddr={{ vm_listen_addr }}'
      - '-httpAuth.username={{ vm_user }}'
      - '-httpAuth.password={{ vm_password }}'
      - '-selfScrapeInterval=15s'
    volumes:
      - /var/lib/victoria-metrics:/storage
  become: true
  tags:
    - victoriametrics
    - monitoring_server
