# =========================================
#      INSTALL 3X-UI IF NOT INSTALLED
# =========================================
- name: Check if 3x-ui files are present
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items:
    - /usr/local/x-ui/x-ui  # Main binary
    - /usr/bin/x-ui         # Management script
  register: x_ui_files
  when: not x_ui_installed_skipped | default(false)

- name: Determine if 3x-ui is installed
  ansible.builtin.set_fact:
    x_ui_installed: "{{ x_ui_files.results | selectattr('stat.exists', 'equalto', true) | list | length > 0 }}"

- name: Download 3x-ui install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/mhsanaei/3x-ui/v2.8.11/install.sh
    dest: /tmp/install.sh
    mode: '0755'
  when: not x_ui_installed

- name: Install 3x-ui non‑interactively using a wrapper script
  ansible.builtin.script: run_installation_interactive.sh
  become: true
  environment:
    UI_PANEL_PORT: "{{ x_ui_panel_port }}"
    UI_PANEL_ACME_PORT: "{{ x_ui_panel_acme_port }}"
    TERM: linux   # helps some prompts behave as if interactive
  args:
    executable: bash
  timeout: 600
  when: not x_ui_installed
#  TODO add update to a certain version


- name: Allow traffic on port 80 for ACME
  community.general.ufw:
    rule: allow
    port: "{{ x_ui_panel_acme_port }}"
  become: true
  tags:
    - firewall

- name: Allow traffic on 3X-UI panel port
  community.general.ufw:
    rule: allow
    port: "{{ x_ui_panel_port }}"
    proto: tcp
  become: true
  tags:
    - firewall


# =========================================
#        UPDATE WEB PAGE CREDENTIALS
# =========================================

- name: Reset 3x-UI Web UI credentials via wrapper script
  ansible.builtin.script: reset_credentials.sh
  become: true
  environment:
    UI_USERNAME: "{{ ui_panel_username }}"
    UI_PASSWORD: "{{ ui_panel_password }}"
    TERM: linux   # helps some prompts behave as if interactive
  args:
    executable: bash
  timeout: 60
